"""
src/kg/ontology_builder.py
Builds the minimal space-domain ontology and saves it as kg_artifacts/ontology.ttl.

Classes  : SpaceMission, Astronaut, SpaceAgency, CelestialBody, Spacecraft, Telescope
Properties: hasAstronaut, launchedBy, landedOn, partOf, locatedIn, discoveredBy,
            isCommanderOf

Usage:
    python -m src.kg.ontology_builder
"""

import argparse
from pathlib import Path

from rdflib import Graph, Literal, Namespace, RDF, RDFS, OWL, URIRef
from rdflib.namespace import XSD

# ── Namespaces ───────────────────────────────────────────────────────────────
SKG = Namespace("http://space-kg.org/ontology/")
WD  = Namespace("http://www.wikidata.org/entity/")


def build_ontology() -> Graph:
    """Create and return the space-domain ontology graph."""
    g = Graph()
    g.bind("skg", SKG)
    g.bind("owl", OWL)
    g.bind("rdfs", RDFS)
    g.bind("xsd", XSD)

    # ── Ontology declaration ─────────────────────────────────────────────────
    onto = SKG[""]
    g.add((onto, RDF.type, OWL.Ontology))
    g.add((onto, RDFS.label, Literal("Space Exploration Knowledge Graph Ontology")))
    g.add((onto, RDFS.comment, Literal(
        "Minimal ontology for the space-exploration domain. "
        "Generated by the Web Datamining & Semantics project."
    )))

    # ── Classes ──────────────────────────────────────────────────────────────
    classes = {
        "SpaceMission":  "A crewed or uncrewed mission conducted in outer space.",
        "Astronaut":     "A person trained and certified to travel in space.",
        "SpaceAgency":   "A governmental or commercial organisation conducting space activities.",
        "CelestialBody": "A naturally occurring astronomical object (planet, moon, asteroid …).",
        "Spacecraft":    "A vehicle designed to travel in outer space.",
        "Telescope":     "An instrument for observing distant celestial objects.",
    }
    for name, comment in classes.items():
        cls_uri = SKG[name]
        g.add((cls_uri, RDF.type, OWL.Class))
        g.add((cls_uri, RDFS.label, Literal(name)))
        g.add((cls_uri, RDFS.comment, Literal(comment)))

    # Sub-class relationships
    g.add((SKG["Astronaut"], RDFS.subClassOf, SKG["Person"]))
    g.add((SKG["Telescope"], RDFS.subClassOf, SKG["Spacecraft"]))

    # MissionCommander used by SWRL rule in src/reason/swrl_kb.py
    g.add((SKG["MissionCommander"], RDF.type, OWL.Class))
    g.add((SKG["MissionCommander"], RDFS.subClassOf, SKG["Astronaut"]))
    g.add((SKG["MissionCommander"], RDFS.comment,
           Literal("An astronaut who commands a space mission. Inferred via SWRL.")))

    # Person (super-class, minimal)
    g.add((SKG["Person"], RDF.type, OWL.Class))
    g.add((SKG["Person"], RDFS.label, Literal("Person")))

    # ── Object Properties ────────────────────────────────────────────────────
    object_properties = [
        ("hasAstronaut", "SpaceMission", "Astronaut",
         "Links a mission to a crew member."),
        ("launchedBy",   "SpaceMission", "SpaceAgency",
         "Indicates the agency that launched the mission."),
        ("landedOn",     "SpaceMission", "CelestialBody",
         "The celestial body on which a mission landed."),
        ("partOf",       None,           None,
         "Generic part-of relationship."),
        ("locatedIn",    None,           None,
         "Spatial containment relationship."),
        ("discoveredBy", "CelestialBody", "Person",
         "The person credited with discovering a celestial body."),
        ("isCommanderOf","Astronaut",     "SpaceMission",
         "An astronaut commands a specific mission."),
    ]

    for name, domain, rng, comment in object_properties:
        prop_uri = SKG[name]
        g.add((prop_uri, RDF.type, OWL.ObjectProperty))
        g.add((prop_uri, RDFS.label, Literal(name)))
        g.add((prop_uri, RDFS.comment, Literal(comment)))
        if domain:
            g.add((prop_uri, RDFS.domain, SKG[domain]))
        if rng:
            g.add((prop_uri, RDFS.range, SKG[rng]))

    return g


def save_ontology(g: Graph, out_path: str) -> None:
    out_file = Path(out_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    g.serialize(destination=str(out_file), format="turtle")
    print(f"Ontology saved → {out_file}  ({len(g)} triples)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build space-domain ontology")
    parser.add_argument(
        "--out", default="kg_artifacts/ontology.ttl",
        help="Output Turtle file"
    )
    args = parser.parse_args()
    g = build_ontology()
    save_ontology(g, args.out)


if __name__ == "__main__":
    main()
